name: tazrout_dashboard
description: "Agricultural IoT smart irrigation dashboard for Tazrout."
publish_to: 'none'

#& Environment Configuration
environment:
  sdk: '>=3.11.0 <4.0.0'

#& Project Dependencies
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  dio: ^5.4.3
  web_socket_channel: ^3.0.1
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1
  phosphor_flutter: ^2.1.0
  intl: ^0.20.2
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.2.4

#& Development Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

#& Flutter Specific Configuration
flutter:
  generate: true
  uses-material-design: true
  assets:
      - assets/icons/Dark/svg/
      - assets/icons/Dark/png/
      - assets/icons/Light/svg/
      - assets/icons/Light/png/
      - assets/images/patterns/svg/
      - assets/images/patterns/png/
      - assets/images/berber_icons/svg/
      - assets/images/berber_icons/png/
      - assets/images/berber_symbols/svg/
      - assets/images/berber_symbols/png/
      - assets/images/berber_typography/svg/
      - assets/images/berber_typography/png/
      - assets/icons/Dark/svg/app_icons/
      - assets/icons/Dark/png/app_icon/
      - assets/icons/Light/svg/app_icons/
      - assets/icons/Light/png/app_icons/
      - assets/images/chart_previews/
      - .env